dist: xenial

language: python

branches:
  except:
    - gh-pages

python:
  - "3.7"

before_install:
  - REDIRECT_TO=/dev/stdout
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda &> ${REDIRECT_TO}
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes --quiet conda &> ${REDIRECT_TO}
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt -c conda-forge
  - conda install codecov -y -c conda-forge

install:
  # - pip install -q coveralls pytest-cov
  - pip install .
cache:
  directories:
    - miniconda

# command to run tests, e.g. python setup.py test
script:
  - py.test tests

after_success:
  - codecov
