sudo: false
branches:
  except:
    - gh-pages

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5.0b3"
 
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  - py.test
