branches:
  except:
    - gh-pages

language: python

python:
    - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # Install conda
  - pip install conda
  - conda init
  - conda update conda --yes
  - deps='pip numpy pandas pytest pytables'
  - conda create -p $HOME/mypy --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/mypy/bin:$PATH
  
# command to run tests, e.g. python setup.py test
script: 
  - python setup.py develop && python setup.py test
